spring:
  h2:
    console:
      enabled: true
  liquibase:
    enabled: false
    change-log: classpath:/db/changelog/changelog-master.xml
  datasource:
    username: user
    password: user
    url: jdbc:h2:mem:pokemon_db;
    driver-class-name: org.h2.Driver
  profiles:
   active: "prod"

server:
  error:
    include-stacktrace: NEVER